trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' 

variables:
  dockerId: ristl17  
  imageName: dispolist

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword) 