version: '3.7'
services:
  dispolist:
    image: ristl17/dispolist:2019-Woche1
    build: .
    environment:
      - 'MongoDb__ConnectionString=mongodb://dispolistdb'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    depends_on: 
      - dispolistdb
    ports:
      - '5000:80'
  dispolistdb:
    image: 'mongo:latest'
    restart: always
    volumes:
      - '/var/dispolist/db:/data/db'
    ports:
      - '29017:27017'